version: '3.8'

services:
  # Banco de Dados
  mongodb:
    image: mongo:6.0
    container_name: neo_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=senhaadmin
    networks:
      - neo-network

  redis:
    image: redis:7.0-alpine
    container_name: neo_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - neo-network

  # Auth Service
  auth-service:
    build: ./auth-service
    container_name: neo_auth
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:senhaadmin@mongodb:27017/neo-auth?authSource=admin
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=supersecretjwtkey123
    depends_on:
      - mongodb
      - redis
    networks:
      - neo-network

  # Wallet Service (Novo Microserviço)
  wallet-service:
    build: ./wallet-service
    container_name: neo_wallet
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:senhaadmin@mongodb:27017/neo-wallet?authSource=admin
      - JWT_SECRET=supersecretjwtkey123
    depends_on:
      - mongodb
    networks:
      - neo-network

  # API Gateway
  api-gateway:
    image: nginx:1.23-alpine
    container_name: neo_gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service
      - wallet-service
    networks:
      - neo-network

  # Frontend (React Native - Expo)
  frontend:
    build: ./frontend
    container_name: neo_frontend
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - neo-network

volumes:
  mongodb_data:
  redis_data:

networks:
  neo-network:
    driver: bridge